# Generated by Django 3.1.4 on 2021-03-24 12:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog', '0002_lislikes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lislikes',
            new_name='Dislikes',
        ),
    ]
